In [257]:
import pandas as pd

In [259]:
gameinfo = pd.read_csv("../CleanData/gameinfo_4_25_25.csv")
team_salaries = pd.read_csv("../CleanData/team_salaries_4_26_25.csv")
team_stats = pd.read_csv("../CleanData/team_stats_04_27_25.csv")

In [260]:
gameinfo = gameinfo.loc[gameinfo["season"] > 1984]
gameinfo

,gid,visteam,hometeam,site,number,daynight,attendance,temp,windspeed,season,vruns,hruns,wteam,lteam
123452,BAL198504080,TEX,BAL,BAL11,0.0,day,50402,0.0,-1.0,1985,2,4,BAL,TEX
123453,BOS198504080,NYA,BOS,BOS07,0.0,day,34282,0.0,-1.0,1985,2,9,BOS,NYA
123454,CIN198504080,MON,CIN,CIN08,0.0,day,52971,0.0,-1.0,1985,1,4,CIN,MON
123455,DET198504080,CLE,DET,DET04,0.0,day,51180,42.0,13.0,1985,4,5,DET,CLE
123456,KCA198504080,TOR,KCA,KAN06,0.0,day,41086,0.0,-1.0,1985,1,2,KCA,TOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214677,SFN202409290,SLN,SFN,SFO03,0.0,day,32348,62.0,8.0,2024,6,1,SLN,SFN
214678,TOR202409290,MIA,TOR,TOR02,0.0,day,31688,69.0,15.0,2024,3,1,MIA,TOR
214679,WAS202409290,PHI,WAS,WAS11,0.0,day,26729,69.0,6.0,2024,6,3,PHI,WAS
214680,ATL202409301,NYN,ATL,ATL03,1.0,day,0,73.0,4.0,2024,8,7,NYN,ATL
214681,ATL202409302,NYN,ATL,ATL03,2.0,day,41561,76.0,7.0,2024,0,3,ATL,NYN

In [262]:
team_salaries = team_salaries.loc[team_salaries["yearID"] < 2025]
team_salaries

      yearID teamID      salary
0       1985    ATL  14807000.0
1       1985    BAL  11560712.0
2       1985    BOS  10897560.0
3       1985    CAL  14427894.0
4       1985    CHA   9846178.0
...      ...    ...         ...
1153    2024    MIA  11473396.0
1154    2024    CLE  50885032.0
1155    2024    TBA  37691876.0
1156    2024    PIT  51220210.0
1157    2024    OAK  28956713.0

[1158 rows x 3 columns]

In [265]:
team_stats = team_stats.drop("Unnamed: 0",axis = 1)
team_stats

,gid,team,left_on_base,bat_doubles,bat_triples,bat_home_runs,bat_stolen_bases,passed_balls_allowed,errors_committed,stolen_bases,date
0,BAL198504080,TEX,5.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,1985-04-08
1,BAL198504080,BAL,6.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1985-04-08
2,BOS198504080,NYA,6.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1985-04-08
3,BOS198504080,BOS,5.0,1.0,0.0,3.0,1.0,1.0,1.0,0.0,1985-04-08
4,CIN198504080,MON,5.0,2.0,1.0,0.0,0.0,0.0,0.0,3.0,1985-04-08
...,...,...,...,...,...,...,...,...,...,...,...
185122,NYA202410280,NYA,8.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,2024-10-28
185123,NYA202410290,LAN,4.0,2.0,0.0,2.0,1.0,0.0,1.0,5.0,2024-10-29
185124,NYA202410290,NYA,6.0,3.0,0.0,3.0,5.0,0.0,0.0,1.0,2024-10-29
185125,NYA202410300,LAN,10.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2024-10-30
185126,NYA202410300,NYA,12.0,2.0,0.0,3.0,0.0,0.0,3.0,0.0,2024-10-30

#Randomly sampling to equally represent Home and Visting Team

In [268]:
import numpy as np

rows_count = gameinfo.shape[0]
samples = np.random.binomial(1, 0.5, rows_count)

samples #Home Team = 0 , Visting Team = 1

array([1, 1, 0, ..., 1, 0, 1])

In [270]:
teams_of_interest = []

home_col_index = gameinfo.columns.get_loc("hometeam")
visit_col_index = gameinfo.columns.get_loc("visteam")

for i in range(len(samples)):
    if samples[i] == 0:
        team = gameinfo.iloc[i, home_col_index]
    else:
        team = gameinfo.iloc[i,visit_col_index]
    teams_of_interest.append(team)

teams_of_interest

['TEX',
 'NYA',
 'CIN',
 'DET',
 'TOR',
 'MIN',
 'CHN',
 'LAN',
 'CHA',
 'NYN',
 'ATL',
 'SEA',
 'SFN',
 'BAL',
 'BOS',
 'MIN',
 'MON',
 'CLE',
 'LAN',
 'TOR',
 'OAK',
 'SDN',
 'NYA',
 'MIN',
 'CHN',
 'CLE',
 'LAN',
 'TOR',
 'CHA',
 'SLN',
 'PHI',
 'OAK',
 'ATL',
 'TOR',
 'CHN',
 'PHI',
 'LAN',
 'NYN',
 'OAK',
 'PIT',
 'MIN',
 'MIL',
 'ATL',
 'BAL',
 'BOS',
 'MON',
 'CLE',
 'HOU',
 'DET',
 'LAN',
 'NYN',
 'OAK',
 'PIT',
 'MIN',
 'MIL',
 'SDN',
 'TOR',
 'BOS',
 'CHN',
 'CLE',
 'HOU',
 'DET',
 'LAN',
 'CIN',
 'CAL',
 'PIT',
 'SEA',
 'MIL',
 'ATL',
 'BOS',
 'CHN',
 'HOU',
 'CAL',
 'OAK',
 'PIT',
 'SDN',
 'SLN',
 'ATL',
 'CHN',
 'BAL',
 'MIL',
 'KCA',
 'LAN',
 'NYA',
 'OAK',
 'NYN',
 'SFN',
 'TEX',
 'CIN',
 'PHI',
 'BAL',
 'MIL',
 'BOS',
 'LAN',
 'MIN',
 'SEA',
 'NYN',
 'MON',
 'TEX',
 'SFN',
 'BAL',
 'BOS',
 'CAL',
 'NYA',
 'SDN',
 'MON',
 'TEX',
 'HOU',
 'SEA',
 'CHA',
 'CIN',
 'KCA',
 'TEX',
 'CHN',
 'NYA',
 'MIN',
 'NYN',
 'LAN',
 'PIT',
 'BAL',
 'HOU',
 'CAL',
 'BOS',
 'SFN',
 'DET',
 'TEX',
 'CHN',
 'CLE',
 'MIN',
 'NYN',
 'SDN',
 'PIT',
 'BAL',
 'ATL',
 'SEA',
 'BOS',
 'SFN',
 'DET',
 'TEX',
 'CHN',
 'NYA',
 'MIN',
 'PHI',
 'SDN',
 'SLN',
 'TOR',
 'OAK',
 'MIL',
 'CLE',
 'HOU',
 'SEA',
 'MON',
 'PIT',
 'ATL',
 'LAN',
 'NYN',
 'TEX',
 'TOR',
 'CAL',
 'MIL',
 'DET',
 'HOU',
 'MIN',
 'MON',
 'NYA',
 'PIT',
 'SDN',
 'SFN',
 'NYN',
 'TEX',
 'KCA',
 'OAK',
 'CHA',
 'CLE',
 'HOU',
 'SEA',
 'MON',
 'BOS',
 'PIT',
 'ATL',
 'SFN',
 'NYN',
 'BAL',
 'TOR',
 'CLE',
 'ATL',
 'SDN',
 'MIL',
 'OAK',
 'SLN',
 'NYA',
 'SEA',
 'SFN',
 'CLE',
 'KCA',
 'NYA',
 'ATL',
 'SDN',
 'DET',
 'MIN',
 'SLN',
 'PIT',
 'PHI',
 'SEA',
 'SFN',
 'TOR',
 'BAL',
 'KCA',
 'NYA',
 'HOU',
 'SDN',
 'MIL',
 'MIN',
 'MON',
 'PIT',
 'PHI',
 'SEA',
 'SFN',
 'TEX',
 'CLE',
 'BOS',
 'NYA',
 'ATL',
 'SDN',
 'MIL',
 'OAK',
 'SLN',
 'PIT',
 'CHN',
 'CAL',
 'CIN',
 'TOR',
 'CAL',
 'CLE',
 'OAK',
 'MON',
 'MIL',
 'TEX',
 'BAL',
 'BOS',
 'CHN',
 'ATL',
 'DET',
 'KCA',
 'HOU',
 'TOR',
 'MON',
 'SDN',
 'SEA',
 'LAN',
 'NYA',
 'CHA',
 'CAL',
 'CHN',
 'ATL',
 'DET',
 'KCA',
 'HOU',
 'MIL',
 'MON',
 'PIT',
 'BOS',
 'SLN',
 'NYA',
 'CAL',
 'MIL',
 'BOS',
 'MON',
 'CAL',
 'CHN',
 'CIN',
 'CLE',
 'CHA',
 'BAL',
 'NYA',
 'OAK',
 'HOU',
 'PIT',
 'SEA',
 'SFN',
 'ATL',
 'CAL',
 'CHN',
 'CIN',
 'CLE',
 'CHA',
 'BAL',
 'NYA',
 'BOS',
 'PHI',
 'PIT',
 'TOR',
 'SLN',
 'MON',
 'CAL',
 'CIN',
 'TEX',
 'CHA',
 'BAL',
 'NYA',
 'OAK',
 'PHI',
 'PIT',
 'SEA',
 'SLN',
 'LAN',
 'PIT',
 'SDN',
 'CAL',
 'LAN',
 'CLE',
 'KCA',
 'SEA',
 'MIN',
 'MON',
 'NYN',
 'CIN',
 'SFN',
 'SLN',
 'DET',
 'TOR',
 'CAL',
 'CHA',
 'KCA',
 'LAN',
 'SEA',
 'MIN',
 'MON',
 'ATL',
 'CIN',
 'SDN',
 'SFN',
 'TEX',
 'TOR',
 'SLN',
 'PIT',
 'SFN',
 'MIN',
 'BOS',
 'CHA',
 'CIN',
 'NYA',
 'PIT',
 'CAL',
 'ATL',
 'NYN',
 'SDN',
 'SLN',
 'TEX',
 'TOR',
 'MIN',
 'OAK',
 'DET',
 'CIN',
 'KCA',
 'PIT',
 'CAL',
 'MON',
 'PHI',
 'SDN',
 'SLN',
 'TEX',
 'SEA',
 'BAL',
 'BOS',
 'DET',
 'HOU',
 'KCA',
 'LAN',
 'MIL',
 'ATL',
 'NYN',
 'SDN',
 'SFN',
 'TEX',
 'TOR',
 'ATL',
 'KCA',
 'CHA',
 'PHI',
 'DET',
 'MON',
 'MIN',
 'NYN',
 'BAL',
 'BOS',
 'CLE',
 'PHI',
 'DET',
 'HOU',
 'LAN',
 'OAK',
 'MIN',
 'SLN',
 'SFN',
 'CAL',
 'ATL',
 'SEA',
 'BAL',
 'CLE',
 'HOU',
 'LAN',
 'OAK',
 'DET',
 'MON',
 'TEX',
 'SLN',
 'SFN',
 'TOR',
 'PHI',
 'BAL',
 'CLE',
 'NYN',
 'DET',
 'CIN',
 'NYA',
 'CHN',
 'CAL',
 'TEX',
 'BOS',
 'SLN',
 'KCA',
 'TOR',
 'MON',
 'NYN',
 'DET',
 'PHI',
 'CIN',
 'SEA',
 'ATL',
 'CAL',
 'CHA',
 'BOS',
 'SLN',
 'MIL',
 'MIN',
 'SDN',
 'SFN',
 'OAK',
 'LAN',
 'PIT',
 'SEA',
 'CHN',
 'NYA',
 'CHA',
 'BOS',
 'SLN',
 'MIL',
 'MIN',
 'MON',
 'SFN',
 'OAK',
 'LAN',
 'CIN',
 'BAL',
 'DET',
 'CHN',
 'BOS',
 'MON',
 'SDN',
 'SFN',
 'HOU',
 'ATL',
 'TEX',
 'CHA',
 'DET',
 'CIN',
 'MIL',
 'BOS',
 'MON',
 'OAK',
 'PHI',
 'PIT',
 'NYA',
 'ATL',
 'KCA',
 'TOR',
 'CAL',
 'CIN',
 'CLE',
 'BOS',
 'LAN',
 'SDN',
 'BAL',
 'SFN',
 'PIT',
 'SEA',
 'SLN',
 'TEX',
 'TOR',
 'TOR',
 'OAK',
 'NYA',
 'BOS',
 'PIT',
 'CAL',
 'HOU',
 'CIN',
 'CLE',
 'KCA',
 'MIL',
 'MON',
 'NYN',
 'NYA',
 'PHI',
 'SEA',
 'BOS',
 'PIT',
 'BAL',
 'CHN',
 'SLN',
 'TOR',
 'CHA',
 'MIN',
 'SFN',
 'LAN',
 'NYA',
 'SDN',
 'DET',
 'BOS',
 'ATL',
 'BAL',
 'HOU',
 'SLN',
 'TOR',
 'CHA',
 'MIN',
 'SFN',
 'LAN',
 'OAK',
 'PHI',
 'DET',
 'TEX',
 'BOS',
 'BAL',
 'CIN',
 'PIT',
 'TEX',
 'MIL',
 'SFN',
 'NYN',
 'OAK',
 'SDN',
 'SEA',
 'SLN',
 'CHA',
 'CHN',
 'HOU',
 'TEX',
 'CLE',
 'SDN',
 'SLN',
 'SEA',
 'BOS',
 'CHA',
 'CHN',
 'OAK',
 'HOU',
 'KCA',
 'LAN',
 'MIL',
 'NYA',
 'MON',
 'SFN',
 'SLN',
 'SEA',
 'BOS',
 'KCA',
 'OAK',
 'LAN',
 'CAL',
 'MON',
 'SFN',
 'OAK',
 'BOS',
 'CHA',
 'CAL',
 'HOU',
 'MON',
 'MIN',
 'SEA',
 'ATL',
 'NYN',
 'PHI',
 'CIN',
 'TOR',
 'BAL',
 'BOS',
 'KCA',
 'DET',
 'CHN',
 'MON',
 'MIL',
 'SEA',
 'PIT',
 'NYN',
 'PHI',
 'CIN',
 'CLE',
 'BAL',
 'BOS',
 'CHA',
 'CAL',
 'HOU',
 'MON',
 'MIN',
 'NYA',
 'PIT',
 'NYN',
 'SFN',
 'SLN',
 'TOR',
 'CLE',
 'BAL',
 'BOS',
 'SEA',
 'NYN',
 'NYA',
 'PHI',
 'MON',
 'SLN',
 'CHA',
 'BAL',
 'BOS',
 'ATL',
 'CIN',
 'DET',
 'MIL',
 'NYN',
 'OAK',
 'SDN',
 'MON',
 'SLN',
 'CHA',
 'TOR',
 'BAL',
 'ATL',
 'PIT',
 'DET',
 'MIL',
 'NYN',
 'PHI',
 'MON',
 'SLN',
 'TOR',
 'CHN',
 'SEA',
 'NYA',
 'TEX',
 'DET',
 'ATL',
 'BAL',
 'CAL',
 'CHN',
 'CIN',
 'SDN',
 'CLE',
 'HOU',
 'NYA',
 'MIN',
 'SLN',
 'TEX',
 'PHI',
 'DET',
 'ATL',
 'BAL',
 'KCA',
 'PIT',
 'SDN',
 'CLE',
 'SFN',
 'NYA',
 'MIN',
 'NYN',
 'TEX',
 'PHI',
 'DET',
 'ATL',
 'BOS',
 'CAL',
 'PIT',
 'CIN',
 'CLE',
 'HOU',
 'NYA',
 'CHA',
 'NYN',
 'SLN',
 'TEX',
 'TEX',
 'MON',
 'DET',
 'ATL',
 'MIL',
 'TEX',
 'LAN',
 'CLE',
 'BAL',
 'SDN',
 'CHN',
 'TOR',
 'KCA',
 'NYN',
 'SLN',
 'CHA',
 'SFN',
 'MIL',
 'CAL',
 'HOU',
 'MON',
 'TOR',
 'OAK',
 'PHI',
 'PIT',
 'CHA',
 'ATL',
 'MIL',
 'TEX',
 'BAL',
 'SDN',
 'CHN',
 'NYA',
 'KCA',
 'PHI',
 'SEA',
 'ATL',
 'MIL',
 'BOS',
 'CHA',
 'CHN',
 'NYN',
 'PIT',
 'SEA',
 'SFN',
 'TEX',
 'CIN',
 'MIL',
 'TOR',
 'CHA',
 'CHN',
 'CLE',
 'LAN',
 'NYN',
 'DET',
 'PHI',
 'KCA',
 'SFN',
 'TEX',
 'ATL',
 'BAL',
 'BOS',
 'CAL',
 'SLN',
 'CLE',
 'LAN',
 'NYN',
 'DET',
 'PHI',
 'KCA',
 'SDN',
 'TEX',
 'ATL',
 'BAL',
 'BOS',
 'CHA',
 'CHN',
 'OAK',
 'OAK',
 'HOU',
 'MON',
 'DET',
 'PIT',
 'KCA',
 'SDN',
 'SFN',
 'TEX',
 'HOU',
 'NYA',
 'DET',
 'MIN',
 'LAN',
 'TOR',
 'PIT',
 'CHN',
 'CIN',
 'ATL',
 'BAL',
 'OAK',
 'CAL',
 'DET',
 'KCA',
 'LAN',
 'TOR',
 'MON',
 'NYN',
 'SFN',
 'SLN',
 'SEA',
 'ATL',
 'BAL',
 'OAK',
 'CAL',
 'BOS',
 'KCA',
 'SDN',
 'TOR',
 'PIT',
 'NYN',
 'SFN',
 'SLN',
 'SEA',
 'HOU',
 'CHA',
 'CAL',
 'NYA',
 'MIN',
 'PIT',
 'CHN',
 'SFN',
 'PHI',
 'SEA',
 'TOR',
 'CAL',
 'CIN',
 'ATL',
 'NYA',
 'HOU',
 'MIL',
 'MIN',
 'NYN',
 'CLE',
 'PHI',
 'SDN',
 'CHN',
 'BOS',
 'CHA',
 'CIN',
 'DET',
 'KCA',
 'HOU',
 'BAL',
 'TEX',
 'NYN',
 'OAK',
 'PHI',
 'SDN',
 'SLN',
 'TOR',
 'CAL',
 'ATL',
 'DET',
 'SEA',
 'HOU',
 'BAL',
 'TEX',
 'MON',
 'CLE',
 'PHI',
 'SFN',
 'SLN',
 'BOS',
 'BOS',
 'CLE',
 'HOU',
 'MIN',
 'BAL',
 'OAK',
 'SEA',
 'BOS',
 'CAL',
 'NYN',
 'CIN',
 'HOU',
 'MIN',
 'BAL',
 'OAK',
 'PHI',
 'PIT',
 'LAN',
 'SEA',
 'MIL',
 'BOS',
 'CLE',
 'NYN',
 'CIN',
 'HOU',
 'KCA',
 'BAL',
 'CHA',
 'SLN',
 'MON',
 'LAN',
 'SEA',
 'MIL',
 'CHN',
 'CIN',
 'HOU',
 'SLN',
 'PIT',
 'LAN',
 'MIL',
 'BOS',
 'MIN',
 'TOR',
 'KCA',
 'ATL',
 'MON',
 'MIL',
 'CHN',
 'CIN',
 'CLE',
 'SFN',
 'NYN',
 'TEX',
 'BOS',
 'CHA',
 'TOR',
 'KCA',
 'LAN',
 'MON',
 'MIL',
 'PIT',
 'SDN',
 'CLE',
 'HOU',
 'NYN',
 'TEX',
 'BAL',
 'CHA',
 'TOR',
 'KCA',
 'ATL',
 'MON',
 'NYA',
 'PIT',
 'SDN',
 'CLE',
 'SFN',
 'HOU',
 'NYN',
 'TEX',
 'BAL',
 'SEA',
 'OAK',
 'CIN',
 'BOS',
 'CLE',
 'SLN',
 'NYN',
 'PHI',
 'SDN',
 'ATL',
 'CAL',
 'NYA',
 'DET',
 'SEA',
 'KCA',
 'CIN',
 'BOS',
 'CLE',
 'MON',
 'PIT',
 'CHN',
 'SDN',
 'ATL',
 'CAL',
 'NYA',
 'DET',
 'SEA',
 'OAK',
 'MIL',
 'MIN',
 'PIT',
 'PHI',
 'TEX',
 'NYA',
 'NYN',
 'CAL',
 'SFN',
 'CHA',
 'MON',
 'BAL',
 'MIN',
 'TOR',
 'PHI',
 'SDN',
 'SEA',
 'LAN',
 'DET',
 'ATL',
 'BOS',
 'SFN',
 'CLE',
 'HOU',
 'BAL',
 'NYA',
 'OAK',
 'CIN',
 'SDN',
 'SEA',
 ...]

In [271]:
#Two new columns added
gameinfo.loc[:, "team"] = teams_of_interest
gameinfo.loc[:, "Home_Away"] = samples #Home Team = 0 , Visting Team = 1
gameinfo

,gid,visteam,hometeam,site,number,daynight,attendance,temp,windspeed,season,vruns,hruns,wteam,lteam,team,Home_Away
123452,BAL198504080,TEX,BAL,BAL11,0.0,day,50402,0.0,-1.0,1985,2,4,BAL,TEX,TEX,1
123453,BOS198504080,NYA,BOS,BOS07,0.0,day,34282,0.0,-1.0,1985,2,9,BOS,NYA,NYA,1
123454,CIN198504080,MON,CIN,CIN08,0.0,day,52971,0.0,-1.0,1985,1,4,CIN,MON,CIN,0
123455,DET198504080,CLE,DET,DET04,0.0,day,51180,42.0,13.0,1985,4,5,DET,CLE,DET,0
123456,KCA198504080,TOR,KCA,KAN06,0.0,day,41086,0.0,-1.0,1985,1,2,KCA,TOR,TOR,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214677,SFN202409290,SLN,SFN,SFO03,0.0,day,32348,62.0,8.0,2024,6,1,SLN,SFN,SLN,1
214678,TOR202409290,MIA,TOR,TOR02,0.0,day,31688,69.0,15.0,2024,3,1,MIA,TOR,MIA,1
214679,WAS202409290,PHI,WAS,WAS11,0.0,day,26729,69.0,6.0,2024,6,3,PHI,WAS,PHI,1
214680,ATL202409301,NYN,ATL,ATL03,1.0,day,0,73.0,4.0,2024,8,7,NYN,ATL,ATL,0
214681,ATL202409302,NYN,ATL,ATL03,2.0,day,41561,76.0,7.0,2024,0,3,ATL,NYN,NYN,1

In [272]:
#Difference in score "team" - opponent
home_score_col_index = gameinfo.columns.get_loc("hruns")
visit_score_col_index = gameinfo.columns.get_loc("vruns")

score_diff = []

for i in range(len(samples)):
    hruns = gameinfo.iloc[i, home_score_col_index]
    vruns = gameinfo.iloc[i, visit_score_col_index]
    
    if samples[i] == 0:
        score = hruns - vruns
    else:
        score = vruns - hruns
    score_diff.append(score)

score_diff

[-2,
 -7,
 3,
 1,
 -1,
 4,
 1,
 -1,
 2,
 1,
 6,
 3,
 1,
 6,
 9,
 3,
 3,
 -7,
 1,
 1,
 -1,
 3,
 -2,
 -1,
 3,
 -1,
 1,
 1,
 -7,
 -1,
 -3,
 -8,
 -4,
 -5,
 -4,
 -5,
 -3,
 1,
 9,
 2,
 -1,
 5,
 2,
 1,
 5,
 -5,
 -3,
 -2,
 2,
 1,
 1,
 -5,
 1,
 -1,
 1,
 -2,
 2,
 -5,
 2,
 -1,
 2,
 4,
 -4,
 -4,
 -7,
 -6,
 4,
 7,
 -1,
 -1,
 1,
 -2,
 5,
 3,
 3,
 5,
 5,
 -1,
 1,
 -3,
 -1,
 2,
 -4,
 1,
 2,
 1,
 -1,
 5,
 5,
 -1,
 3,
 2,
 -5,
 1,
 -1,
 -4,
 4,
 1,
 -2,
 -1,
 -6,
 1,
 1,
 1,
 -5,
 6,
 -2,
 -4,
 -8,
 7,
 2,
 7,
 3,
 -2,
 -1,
 -2,
 1,
 -9,
 -1,
 -1,
 7,
 -1,
 4,
 -1,
 1,
 4,
 -4,
 -3,
 -4,
 -1,
 1,
 -1,
 -1,
 -2,
 -7,
 -5,
 -1,
 -1,
 3,
 4,
 -3,
 2,
 4,
 -2,
 6,
 -1,
 -5,
 2,
 2,
 3,
 -4,
 -8,
 2,
 -2,
 1,
 1,
 5,
 -2,
 -5,
 -1,
 1,
 2,
 2,
 1,
 -1,
 -5,
 -2,
 1,
 -5,
 -10,
 1,
 2,
 -1,
 1,
 -5,
 -10,
 1,
 1,
 -3,
 -2,
 -2,
 -4,
 1,
 8,
 -6,
 1,
 -3,
 4,
 -1,
 -2,
 4,
 -3,
 4,
 -3,
 -3,
 -2,
 -1,
 -2,
 1,
 1,
 -5,
 -6,
 -4,
 -8,
 1,
 1,
 -6,
 1,
 -1,
 -6,
 1,
 -1,
 2,
 5,
 1,
 5,
 -5,
 -1,
 -1,
 -1,
 -3,
 -1,
 -1,
 1,
 -5,
 -9,
 -2,
 -1,
 -1,
 1,
 -1,
 3,
 1,
 -1,
 -1,
 -1,
 -2,
 2,
 2,
 -1,
 2,
 4,
 -9,
 4,
 -3,
 1,
 -11,
 -4,
 2,
 -5,
 -4,
 -2,
 -3,
 1,
 8,
 -4,
 -1,
 7,
 3,
 1,
 -2,
 -7,
 -1,
 4,
 1,
 -1,
 1,
 7,
 -7,
 -1,
 -5,
 4,
 6,
 1,
 6,
 -10,
 -1,
 14,
 -1,
 -7,
 -6,
 1,
 4,
 12,
 2,
 -6,
 -2,
 3,
 1,
 2,
 -1,
 -7,
 2,
 -5,
 4,
 -1,
 5,
 -1,
 5,
 4,
 3,
 -1,
 1,
 3,
 -5,
 1,
 -2,
 -3,
 -2,
 -2,
 -3,
 -2,
 -3,
 2,
 -2,
 2,
 2,
 2,
 -10,
 9,
 9,
 -5,
 4,
 1,
 3,
 2,
 2,
 1,
 -4,
 6,
 10,
 -1,
 -3,
 -2,
 1,
 -1,
 1,
 -1,
 1,
 -2,
 3,
 2,
 -1,
 1,
 -5,
 5,
 -4,
 6,
 3,
 5,
 -2,
 11,
 -3,
 -3,
 -8,
 3,
 1,
 3,
 -4,
 2,
 5,
 -3,
 -2,
 -4,
 -2,
 -4,
 5,
 1,
 2,
 3,
 -4,
 1,
 2,
 1,
 -6,
 4,
 1,
 3,
 8,
 -4,
 3,
 -1,
 -1,
 2,
 -2,
 -5,
 -1,
 6,
 3,
 10,
 -5,
 3,
 -3,
 -4,
 2,
 -3,
 1,
 6,
 -3,
 -4,
 -2,
 -1,
 16,
 -1,
 -1,
 -1,
 10,
 -1,
 -3,
 -3,
 2,
 -6,
 -1,
 -2,
 2,
 1,
 2,
 -6,
 -2,
 5,
 2,
 3,
 -1,
 1,
 1,
 8,
 5,
 3,
 -8,
 1,
 -5,
 -5,
 -3,
 -1,
 5,
 -2,
 6,
 6,
 -3,
 -2,
 -8,
 1,
 -3,
 -3,
 4,
 -1,
 -4,
 1,
 6,
 -5,
 -1,
 2,
 1,
 6,
 1,
 -5,
 5,
 -3,
 8,
 2,
 -1,
 -2,
 -14,
 1,
 -5,
 -1,
 3,
 -2,
 8,
 5,
 1,
 1,
 1,
 10,
 -3,
 5,
 1,
 -1,
 -3,
 -1,
 1,
 4,
 1,
 3,
 4,
 -2,
 3,
 2,
 -3,
 10,
 1,
 2,
 -2,
 -1,
 2,
 -1,
 4,
 1,
 -1,
 4,
 3,
 2,
 -1,
 7,
 -1,
 -1,
 -1,
 6,
 -2,
 1,
 2,
 3,
 -3,
 -2,
 -2,
 4,
 -1,
 3,
 1,
 -7,
 1,
 -6,
 -2,
 5,
 1,
 -1,
 -2,
 -2,
 -1,
 -12,
 -5,
 6,
 2,
 7,
 2,
 -1,
 -2,
 -2,
 -8,
 5,
 7,
 1,
 -1,
 3,
 6,
 -5,
 -2,
 -1,
 5,
 -1,
 -3,
 -2,
 1,
 7,
 3,
 -1,
 2,
 5,
 4,
 5,
 5,
 5,
 1,
 -1,
 6,
 -6,
 1,
 -1,
 -1,
 -5,
 -2,
 -1,
 -1,
 -7,
 -2,
 5,
 3,
 -4,
 -4,
 -2,
 -5,
 6,
 -1,
 -1,
 -5,
 5,
 -2,
 6,
 -1,
 -7,
 3,
 2,
 5,
 -6,
 3,
 2,
 -1,
 6,
 -5,
 9,
 9,
 3,
 -1,
 1,
 -1,
 1,
 -1,
 5,
 4,
 2,
 -5,
 -1,
 -3,
 2,
 1,
 1,
 -1,
 3,
 1,
 2,
 4,
 -4,
 -1,
 5,
 -2,
 6,
 -1,
 -1,
 3,
 2,
 1,
 -4,
 5,
 -4,
 7,
 4,
 2,
 -2,
 3,
 8,
 -1,
 -2,
 6,
 -5,
 5,
 1,
 -8,
 -4,
 -1,
 -2,
 -5,
 -4,
 -6,
 1,
 -6,
 1,
 -2,
 3,
 -1,
 3,
 5,
 2,
 -2,
 -7,
 4,
 -1,
 3,
 -4,
 -3,
 4,
 -3,
 1,
 -2,
 -1,
 -1,
 -1,
 9,
 7,
 12,
 1,
 -4,
 -2,
 -4,
 5,
 -5,
 4,
 5,
 6,
 4,
 -1,
 -3,
 5,
 7,
 -2,
 -7,
 3,
 -2,
 -1,
 8,
 1,
 -2,
 -1,
 -2,
 5,
 5,
 1,
 2,
 -2,
 11,
 -2,
 3,
 1,
 19,
 11,
 6,
 3,
 -5,
 -1,
 -4,
 -1,
 -2,
 -1,
 1,
 -4,
 -3,
 -7,
 -5,
 1,
 -1,
 -2,
 -1,
 -1,
 -1,
 -3,
 -2,
 -2,
 -6,
 -3,
 2,
 -1,
 5,
 8,
 -1,
 4,
 -1,
 -8,
 1,
 2,
 7,
 2,
 2,
 -1,
 2,
 -2,
 3,
 -1,
 2,
 10,
 -1,
 1,
 9,
 -1,
 8,
 1,
 -2,
 -3,
 1,
 5,
 -9,
 5,
 -1,
 -1,
 -1,
 -4,
 1,
 -3,
 1,
 10,
 -1,
 -7,
 -1,
 -1,
 3,
 -2,
 -4,
 1,
 -2,
 -1,
 4,
 1,
 9,
 -4,
 -3,
 -3,
 4,
 -5,
 4,
 -3,
 -4,
 -10,
 -1,
 -2,
 -6,
 1,
 -4,
 4,
 -1,
 1,
 3,
 -1,
 -1,
 2,
 -11,
 4,
 -1,
 3,
 1,
 -2,
 -1,
 -5,
 8,
 1,
 3,
 2,
 1,
 -2,
 -5,
 3,
 1,
 3,
 -8,
 1,
 5,
 -2,
 -5,
 -3,
 1,
 -4,
 -1,
 -3,
 1,
 -1,
 -1,
 2,
 3,
 1,
 1,
 -2,
 10,
 1,
 2,
 6,
 -4,
 3,
 2,
 4,
 -6,
 1,
 -5,
 7,
 -7,
 7,
 1,
 4,
 -6,
 -1,
 -6,
 2,
 -3,
 4,
 1,
 1,
 -2,
 -3,
 -3,
 1,
 2,
 -1,
 1,
 1,
 -6,
 -3,
 -4,
 -4,
 2,
 -2,
 -1,
 -1,
 -10,
 -2,
 -9,
 -6,
 1,
 1,
 2,
 1,
 -3,
 1,
 -2,
 -1,
 -4,
 5,
 1,
 2,
 1,
 9,
 2,
 -3,
 5,
 2,
 -2,
 -2,
 -1,
 2,
 -12,
 -1,
 -8,
 -6,
 1,
 -4,
 6,
 1,
 3,
 -1,
 7,
 -6,
 -1,
 3,
 -1,
 1,
 2,
 -1,
 -1,
 -2,
 -7,
 -1,
 4,
 -4,
 -3,
 -1,
 -3,
 -6,
 2,
 1,
 -7,
 -4,
 3,
 -1,
 -1,
 -2,
 1,
 3,
 -5,
 3,
 -1,
 -8,
 9,
 -3,
 -1,
 -1,
 -4,
 -1,
 -9,
 -1,
 -5,
 5,
 2,
 1,
 4,
 -3,
 -9,
 7,
 -4,
 -1,
 -1,
 -1,
 3,
 1,
 2,
 5,
 6,
 2,
 -1,
 -1,
 2,
 8,
 6,
 -1,
 -3,
 -5,
 -9,
 6,
 -5,
 2,
 3,
 3,
 -6,
 -3,
 -1,
 1,
 ...]

In [273]:
gameinfo.loc[:, "score_diff"] = score_diff
gameinfo

,gid,visteam,hometeam,site,number,daynight,attendance,temp,windspeed,season,vruns,hruns,wteam,lteam,team,Home_Away,score_diff
123452,BAL198504080,TEX,BAL,BAL11,0.0,day,50402,0.0,-1.0,1985,2,4,BAL,TEX,TEX,1,-2
123453,BOS198504080,NYA,BOS,BOS07,0.0,day,34282,0.0,-1.0,1985,2,9,BOS,NYA,NYA,1,-7
123454,CIN198504080,MON,CIN,CIN08,0.0,day,52971,0.0,-1.0,1985,1,4,CIN,MON,CIN,0,3
123455,DET198504080,CLE,DET,DET04,0.0,day,51180,42.0,13.0,1985,4,5,DET,CLE,DET,0,1
123456,KCA198504080,TOR,KCA,KAN06,0.0,day,41086,0.0,-1.0,1985,1,2,KCA,TOR,TOR,1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214677,SFN202409290,SLN,SFN,SFO03,0.0,day,32348,62.0,8.0,2024,6,1,SLN,SFN,SLN,1,5
214678,TOR202409290,MIA,TOR,TOR02,0.0,day,31688,69.0,15.0,2024,3,1,MIA,TOR,MIA,1,2
214679,WAS202409290,PHI,WAS,WAS11,0.0,day,26729,69.0,6.0,2024,6,3,PHI,WAS,PHI,1,3
214680,ATL202409301,NYN,ATL,ATL03,1.0,day,0,73.0,4.0,2024,8,7,NYN,ATL,ATL,0,-1
214681,ATL202409302,NYN,ATL,ATL03,2.0,day,41561,76.0,7.0,2024,0,3,ATL,NYN,NYN,1,-3

In [274]:
#merged with teamstats data
merge_cols = ["gid", "team"]

merged_1 = pd.merge(gameinfo, team_stats, on=merge_cols, how='left')
merged_1

,gid,visteam,hometeam,site,number,daynight,attendance,temp,windspeed,season,...,score_diff,left_on_base,bat_doubles,bat_triples,bat_home_runs,bat_stolen_bases,passed_balls_allowed,errors_committed,stolen_bases,date
0,BAL198504080,TEX,BAL,BAL11,0.0,day,50402,0.0,-1.0,1985,...,-2,5.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,1985-04-08
1,BOS198504080,NYA,BOS,BOS07,0.0,day,34282,0.0,-1.0,1985,...,-7,6.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1985-04-08
2,CIN198504080,MON,CIN,CIN08,0.0,day,52971,0.0,-1.0,1985,...,3,8.0,3.0,0.0,0.0,3.0,0.0,0.0,0.0,1985-04-08
3,DET198504080,CLE,DET,DET04,0.0,day,51180,42.0,13.0,1985,...,1,10.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1985-04-08
4,KCA198504080,TOR,KCA,KAN06,0.0,day,41086,0.0,-1.0,1985,...,-1,7.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1985-04-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91226,SFN202409290,SLN,SFN,SFO03,0.0,day,32348,62.0,8.0,2024,...,5,6.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2024-09-29
91227,TOR202409290,MIA,TOR,TOR02,0.0,day,31688,69.0,15.0,2024,...,2,6.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2024-09-29
91228,WAS202409290,PHI,WAS,WAS11,0.0,day,26729,69.0,6.0,2024,...,3,5.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2024-09-29
91229,ATL202409301,NYN,ATL,ATL03,1.0,day,0,73.0,4.0,2024,...,-1,9.0,1.0,0.0,2.0,2.0,0.0,0.0,2.0,2024-09-30
91230,ATL202409302,NYN,ATL,ATL03,2.0,day,41561,76.0,7.0,2024,...,-3,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2024-09-30

In [275]:
#Merged with salary data
merged_2 = pd.merge(
    merged_1, 
    team_salaries, 
    left_on=["season", "team"], 
    right_on=["yearID", "teamID"], 
    how="left"
)
merged_2

,gid,visteam,hometeam,site,number,daynight,attendance,temp,windspeed,season,...,bat_triples,bat_home_runs,bat_stolen_bases,passed_balls_allowed,errors_committed,stolen_bases,date,yearID,teamID,salary
0,BAL198504080,TEX,BAL,BAL11,0.0,day,50402,0.0,-1.0,1985,...,0.0,0.0,0.0,1.0,0.0,0.0,1985-04-08,1985,TEX,7676500.0
1,BOS198504080,NYA,BOS,BOS07,0.0,day,34282,0.0,-1.0,1985,...,0.0,0.0,0.0,0.0,0.0,1.0,1985-04-08,1985,NYA,14238204.0
2,CIN198504080,MON,CIN,CIN08,0.0,day,52971,0.0,-1.0,1985,...,0.0,0.0,3.0,0.0,0.0,0.0,1985-04-08,1985,CIN,8359917.0
3,DET198504080,CLE,DET,DET04,0.0,day,51180,42.0,13.0,1985,...,0.0,0.0,1.0,0.0,0.0,1.0,1985-04-08,1985,DET,10348143.0
4,KCA198504080,TOR,KCA,KAN06,0.0,day,41086,0.0,-1.0,1985,...,0.0,0.0,1.0,0.0,1.0,0.0,1985-04-08,1985,TOR,8812550.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91226,SFN202409290,SLN,SFN,SFO03,0.0,day,32348,62.0,8.0,2024,...,0.0,1.0,0.0,0.0,1.0,0.0,2024-09-29,2024,SLN,112213666.0
91227,TOR202409290,MIA,TOR,TOR02,0.0,day,31688,69.0,15.0,2024,...,0.0,0.0,0.0,0.0,0.0,0.0,2024-09-29,2024,MIA,11473396.0
91228,WAS202409290,PHI,WAS,WAS11,0.0,day,26729,69.0,6.0,2024,...,0.0,0.0,1.0,0.0,0.0,1.0,2024-09-29,2024,PHI,226203004.0
91229,ATL202409301,NYN,ATL,ATL03,1.0,day,0,73.0,4.0,2024,...,0.0,2.0,2.0,0.0,0.0,2.0,2024-09-30,2024,ATL,156338167.0
91230,ATL202409302,NYN,ATL,ATL03,2.0,day,41561,76.0,7.0,2024,...,0.0,0.0,0.0,0.0,1.0,0.0,2024-09-30,2024,NYN,189012437.0

In [276]:
col_dtype_conv = ["gid","visteam","hometeam","site","daynight","wteam", "lteam","team", "teamID"]
merged_2.loc[:,col_dtype_conv] = merged_2.loc[:,col_dtype_conv].astype("string")

In [277]:
merged_2['daynight'] = merged_2['daynight'].map({'day': 1, 'night': 0})

In [280]:
merged_2

,gid,visteam,hometeam,site,number,daynight,attendance,temp,windspeed,season,...,bat_triples,bat_home_runs,bat_stolen_bases,passed_balls_allowed,errors_committed,stolen_bases,date,yearID,teamID,salary
0,BAL198504080,TEX,BAL,BAL11,0.0,1,50402,0.0,-1.0,1985,...,0.0,0.0,0.0,1.0,0.0,0.0,1985-04-08,1985,TEX,7676500.0
1,BOS198504080,NYA,BOS,BOS07,0.0,1,34282,0.0,-1.0,1985,...,0.0,0.0,0.0,0.0,0.0,1.0,1985-04-08,1985,NYA,14238204.0
2,CIN198504080,MON,CIN,CIN08,0.0,1,52971,0.0,-1.0,1985,...,0.0,0.0,3.0,0.0,0.0,0.0,1985-04-08,1985,CIN,8359917.0
3,DET198504080,CLE,DET,DET04,0.0,1,51180,42.0,13.0,1985,...,0.0,0.0,1.0,0.0,0.0,1.0,1985-04-08,1985,DET,10348143.0
4,KCA198504080,TOR,KCA,KAN06,0.0,1,41086,0.0,-1.0,1985,...,0.0,0.0,1.0,0.0,1.0,0.0,1985-04-08,1985,TOR,8812550.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91226,SFN202409290,SLN,SFN,SFO03,0.0,1,32348,62.0,8.0,2024,...,0.0,1.0,0.0,0.0,1.0,0.0,2024-09-29,2024,SLN,112213666.0
91227,TOR202409290,MIA,TOR,TOR02,0.0,1,31688,69.0,15.0,2024,...,0.0,0.0,0.0,0.0,0.0,0.0,2024-09-29,2024,MIA,11473396.0
91228,WAS202409290,PHI,WAS,WAS11,0.0,1,26729,69.0,6.0,2024,...,0.0,0.0,1.0,0.0,0.0,1.0,2024-09-29,2024,PHI,226203004.0
91229,ATL202409301,NYN,ATL,ATL03,1.0,1,0,73.0,4.0,2024,...,0.0,2.0,2.0,0.0,0.0,2.0,2024-09-30,2024,ATL,156338167.0
91230,ATL202409302,NYN,ATL,ATL03,2.0,1,41561,76.0,7.0,2024,...,0.0,0.0,0.0,0.0,1.0,0.0,2024-09-30,2024,NYN,189012437.0

In [281]:
merged_2.dtypes

gid                      object
visteam                  object
hometeam                 object
site                     object
number                  float64
daynight                  int64
attendance                int64
temp                    float64
windspeed               float64
season                    int64
vruns                     int64
hruns                     int64
wteam                    object
lteam                    object
team                     object
Home_Away                 int32
score_diff                int64
left_on_base            float64
bat_doubles             float64
bat_triples             float64
bat_home_runs           float64
bat_stolen_bases        float64
passed_balls_allowed    float64
errors_committed        float64
stolen_bases            float64
date                     object
yearID                    int64
teamID                   object
salary                  float64
dtype: object

In [282]:
merged_2.isna().sum()
#21 null values for both lteam, wteam column. 21 undecided / tied games. This is an anomaly in basbeall
#Will be dropped

gid                      0
visteam                  0
hometeam                 0
site                     0
number                   0
daynight                 0
attendance               0
temp                     0
windspeed                0
season                   0
vruns                    0
hruns                    0
wteam                   21
lteam                   21
team                     0
Home_Away                0
score_diff               0
left_on_base             0
bat_doubles              0
bat_triples              0
bat_home_runs            0
bat_stolen_bases         0
passed_balls_allowed     0
errors_committed         0
stolen_bases             0
date                     0
yearID                   0
teamID                   0
salary                   0
dtype: int64

In [283]:
merged_2 = merged_2.dropna()
merged_2.isna().sum()

gid                     0
visteam                 0
hometeam                0
site                    0
number                  0
daynight                0
attendance              0
temp                    0
windspeed               0
season                  0
vruns                   0
hruns                   0
wteam                   0
lteam                   0
team                    0
Home_Away               0
score_diff              0
left_on_base            0
bat_doubles             0
bat_triples             0
bat_home_runs           0
bat_stolen_bases        0
passed_balls_allowed    0
errors_committed        0
stolen_bases            0
date                    0
yearID                  0
teamID                  0
salary                  0
dtype: int64

In [284]:
merged_2.to_csv("../CleanData/master_set_without_imputation_4_27_25.csv")

#Imputing Data For Missing Values

In [286]:
#check 0 val for attendance , temp, windspeed , for these cols NaNs were replaced with 0s.
#Original data did not have 0 vals in these cols

In [287]:
averages = merged_2.groupby("site")[["attendance", "temp", "windspeed"]].mean().reset_index()
averages

     site    attendance       temp  windspeed
0   ANA01  32576.588998  64.896933   5.383813
1   ARL01  23294.631362  54.270977   3.724897
2   ARL02  32062.067821  84.176527  10.766234
3   ARL03  26288.745763  74.076271   1.347458
4   ATL01  25651.866167  47.180942   3.279443
..    ...           ...        ...        ...
67  TOR01  31652.455587  16.409742   1.117479
68  TOR02  31817.535531  66.169963   5.543956
69  WAS10  28168.769547  76.880658   9.144033
70  WAS11  26596.712661  77.057619   6.442002
71  WIL02   2404.571429  75.142857   5.000000

[72 rows x 4 columns]

In [288]:
attendance_col_index = merged_2.columns.get_loc("attendance")
temp_col_index = merged_2.columns.get_loc("temp")
windsp_col_index = merged_2.columns.get_loc("windspeed")
site_col_index = merged_2.columns.get_loc("site")

for i in range(merged_2.shape[0]):
    attendance = merged_2.iloc[i,attendance_col_index]
    temp = merged_2.iloc[i,temp_col_index]
    windspeed = merged_2.iloc[i,windsp_col_index]
    site = merged_2.iloc[i,site_col_index]

    if attendance == 0:
        merged_2.iloc[i,attendance_col_index] = int(averages.loc[averages["site"] == site,"attendance"].values[0])
    if windspeed == 0:
        merged_2.iloc[i,windsp_col_index] = averages.loc[averages["site"] == site,"windspeed"].values[0]
    if temp == 0:
        merged_2.iloc[i,temp_col_index] = averages.loc[averages["site"] == site,"temp"].values[0]

In [289]:
zero_counts = merged_2[["temp", "attendance", "windspeed"]].eq(0).sum() 
print(zero_counts)

temp           0
attendance     0
windspeed     12
dtype: int64

In [290]:
averages["windspeed"].eq(0).sum() #there are 2 site with average 0 windspeed

2

In [291]:
merged_2.to_csv("../CleanData/master_set_with_imputation_4_27_25.csv")

In [292]:
"""
Summary
Randomly sampled each row to determine if team of interest is home or away.
    team of interest for each row is recorded in column "team"
    whether they are home or away is recorded in column "home_away" Home Team = 0 , Visting Team = 1

Merged gameinfo df to teamstats df on columns "team" and "gameid" -> merged_1 df

Merged merged_1 df with team_salaries on "season" and "team" -> merged_2 df

Checked for Null Values.Only 21 null rows of undecided games. Dropped because this is an anomaly in baseball. Games do not end in ties

Imputed values for "temp" , "attendance" and "windspeed"
    Originally I replaced NaN with 0s. Imputted 0s with averages of temp, attendance, windspeed based on the "site"

Hardencoded "daynight" column : day = 1 , night = 0

Added a score_diff column , score of team under "team" column - opponent
"""

'\nSummary\nRandomly sampled each row to determine if team of interest is home or away.\n    team of interest for each row is recorded in column "team"\n    whether they are home or away is recorded in column "home_away" Home Team = 0 , Visting Team = 1\n\nMerged gameinfo df to teamstats df on columns "team" and "gameid" -> merged_1 df\n\nMerged merged_1 df with team_salaries on "season" and "team" -> merged_2 df\n\nChecked for Null Values.Only 21 null rows of undecided games. Dropped because this is an anomaly in baseball. Games do not end in ties\n\nImputed values for "temp" , "attendance" and "windspeed"\n    Originally I replaced NaN with 0s. Imputted 0s with averages of temp, attendance, windspeed based on the "site"\n\nHardencoded "daynight" column : day = 1 , night = 0\n'